application: djangae-test-01
module: default
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /_ah/(mapreduce|queue|warmup|internalupload).*
  script: mlgae.wsgi.application
  login: admin
  secure: always

- url: /static/admin/
  static_dir: sitepackages/django/contrib/admin/static/admin/
  secure: always

- url: /static/rest_framework/
  static_dir: sitepackages/rest_framework/static/rest_framework/
  secure: always

# Set Django admin to be login:admin as well as Django's is_staff restriction
- url: /admin.*
  script: mlgae.wsgi.application
  secure: always
  login: admin

- url: /.*
  script: mlgae.wsgi.application
  secure: always

builtins:
- remote_api: on

skip_files:
    - manage.py
    - README.md
    - install_deps
    - rename_mlage_app
    - requirements.txt
    - sitepackages/google_appengine*
    - sitepackages/debug_toolbar*
    - sitepackages/django_extensions*
    - \.storage.*
    - \.git
    - (.*)\.pyc
